import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readFile, stat} from 'node:fs/promises';
import {isAllowedTarget, telegramCall, validateInitData, validateRichHtml} from './telegram.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../docs');
const port = Number(process.env.PORT || 3000);
const maxBody = 512 * 1024;
const mime = new Map([['.html','text/html; charset=utf-8'],['.js','text/javascript; charset=utf-8'],['.css','text/css; charset=utf-8'],['.json','application/json; charset=utf-8'],['.svg','image/svg+xml'],['.png','image/png'],['.ico','image/x-icon']]);

function json(res,status,body,extraHeaders={}){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':data.length,'cache-control':'no-store','x-content-type-options':'nosniff',...extraHeaders});res.end(data)}
function corsHeaders(req,env){const origin=String(req.headers.origin||'');if(!origin)return{};const allowed=new Set(String(env.ALLOWED_ORIGINS||'https://romastefale.github.io').split(',').map(v=>v.trim()).filter(Boolean));if(!allowed.has(origin))return{'vary':'Origin'};return{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'86400','vary':'Origin'}}
async function bodyJson(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>maxBody)throw Object.assign(new Error('Corpo da requisição excede o limite'),{status:413});chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}catch{throw Object.assign(new Error('JSON inválido'),{status:400})}}
async function send(req,res,{token,env,fetchImpl,headers={}}){if(!token)return json(res,503,{ok:false,error:'BOT_TOKEN não configurado no servidor'},headers);const input=await bodyJson(req);const initData=typeof input.initData==='string'?input.initData:'';const validated=validateInitData(initData,token,{maxAgeSeconds:Number(env.INIT_DATA_MAX_AGE||86400)});if(!validated.ok)return json(res,401,{ok:false,error:`Sessão Telegram inválida: ${validated.error}`},headers);const chatId=typeof input.chatId==='number'||typeof input.chatId==='string'?String(input.chatId).trim():'';if(!isAllowedTarget(chatId,validated,env))return json(res,403,{ok:false,error:'Destino não autorizado para esta Mini App'},headers);const checked=validateRichHtml(input.html);if(!checked.ok)return json(res,400,{ok:false,error:`Conteúdo inválido: ${checked.error}`},headers);const richMessage={html:checked.html};if(input.isRtl===true)richMessage.is_rtl=true;if(input.skipEntityDetection===true)richMessage.skip_entity_detection=true;try{const result=await telegramCall(token,'sendRichMessage',{chat_id:chatId,rich_message:richMessage,disable_notification:input.disableNotification===true,protect_content:input.protectContent===true},{fetchImpl});return json(res,200,{ok:true,result:result.result},headers)}catch(error){return json(res,502,{ok:false,error:error instanceof Error?error.message:'Falha ao chamar Telegram'},headers)}}
async function serveStatic(req,res){const url=new URL(req.url,'http://local');let pathname=decodeURIComponent(url.pathname);if(pathname==='/')pathname='/index.html';const candidate=path.resolve(root,'.'+pathname);if(!candidate.startsWith(root+path.sep)&&candidate!==root)return json(res,403,{ok:false,error:'forbidden'});try{const info=await stat(candidate);if(!info.isFile())throw new Error('not_file');const data=await readFile(candidate);res.writeHead(200,{'content-type':mime.get(path.extname(candidate))||'application/octet-stream','content-length':data.length,'cache-control':path.extname(candidate)==='.html'?'no-cache':'public, max-age=300','x-content-type-options':'nosniff'});res.end(data)}catch{if(pathname!=='/index.html'&&!path.extname(pathname)){req.url='/index.html';return serveStatic(req,res)}return json(res,404,{ok:false,error:'not_found'})}}
export function createServer({botToken=process.env.BOT_TOKEN||'',env=process.env,fetchImpl=fetch}={}){const token=botToken;return http.createServer(async(req,res)=>{try{const headers=corsHeaders(req,env);if(req.method==='OPTIONS'&&req.url?.startsWith('/api/')){res.writeHead(204,headers);return res.end()}if(req.method==='GET'&&req.url?.startsWith('/api/health'))return json(res,200,{ok:true,botConfigured:Boolean(token),sendScope:env.SEND_SCOPE||'self'},headers);if(req.method==='POST'&&req.url?.startsWith('/api/send'))return await send(req,res,{token,env,fetchImpl,headers});if(req.method==='GET'||req.method==='HEAD')return await serveStatic(req,res);return json(res,405,{ok:false,error:'method_not_allowed'})}catch(error){const status=Number(error?.status)||500;console.error(error);return json(res,status,{ok:false,error:status>=500?'Erro interno':error.message})}})}
if(process.argv[1]===fileURLToPath(import.meta.url)){createServer().listen(port,async()=>{console.log(`RMDtxtML http://localhost:${port}`);const token=process.env.BOT_TOKEN||'';const appUrl=process.env.APP_URL||'';if(token&&/^https:\/\//i.test(appUrl)){try{await telegramCall(token,'setChatMenuButton',{menu_button:{type:'web_app',text:'RMDtxtML',web_app:{url:appUrl}}});console.log(`Telegram menu configured: ${appUrl}`)}catch(error){console.error('Could not configure Telegram menu:',error instanceof Error?error.message:error)}}})}
